@startuml
hide empty description

'state "<b>TEMP</b>" as TEMP: <i>TEMP</i>'
state Common: <i>Resources across threads (<b>!!</b> indicate changes to common resources)</i>
state Common: \n- TX socket
state Common: - RX socket
state Common: - UART queue buffer
state Common: - SPI data buffer
state "<b>Common resources</b>" as Common

'Main thread'
state "<b>Thread main</b>" as Main
state "<b>Setup</b>" as Main_Setup: <i>DECT, device and main setup</i>
state Main_Setup {
  state "<b>Start thread UART</b>" as Main_Thread_UART
  state "<b>Open common sockets</b>" as Main_Sockets: <i>Open common TX and RX sockets</i>
  state "<b>Start thread FT</b>" as Main_Thread_FT

  [*]--> Main_Thread_UART
  Main_Thread_UART --> Main_Sockets: None
  Main_Sockets --> Main_Thread_FT: None
}

state "<b>Main idle</b>" as Main_Idle: <i>Listen for data on RX socket</i>
state "<b>Extend packet</b>" as Main_Extend: <i>Add delay information to packet</i>
state "<b>UART queue</b>" as Main_UART_Send: <i>Queue data to send on UART</i>

[*] --> Main
Main --> Main_Setup: None
Main_Setup --> Main_Idle: None
Main_Idle --> Main_Idle: Other data received
Main_Idle --> Main_Extend: Image data received\n(Edge device)
Main_Idle --> Main_UART_Send: Image data received\n(Relay device)
Main_Extend --> Main_UART_Send: None
Main_UART_Send --> Main_Idle: None

'FT thread'
state "<b>Thread FT</b>" as FT
state "<b>Channel scan</b>" as FT_Scan: <i>Scan over all channels in band</i>
state "<b>Network beacon</b>" as FT_Beacon: <i>Start network beacon on channel <b>x</b>
state "<b>Association idle" as FT_Assoc_Idle: <i>Wait for association request from PT</i>
state "<b>Association response</b>" as FT_Assoc_Resp: <i>Accept association with PT</i>
state "<b>Association drop</b>" as FT_Assoc_Drop: <i>Drop association with PT</i>
state "<b>SYNC FT" as FT_SYNC: <i>Start SYNC process as FT</i>

FT --> FT_Scan: None
FT_Scan --> FT_Beacon: Best\nchannel <b>x</b>
FT_Beacon --> FT_Assoc_Idle: Beacon\nsuccess
FT_Assoc_Idle --> FT_Beacon: Timeout
FT_Assoc_Idle --> FT_Assoc_Resp: Incoming\nrequest
FT_Assoc_Resp --> FT_Assoc_Idle: Association\nfailed
FT_Assoc_Resp --> FT_SYNC: Association\nsuccess
FT_SYNC --> FT_Assoc_Idle: SYNC\nsuccess
FT_SYNC --> FT_SYNC: Timeout (<b>n</b> retries)
FT_SYNC --> FT_Assoc_Drop: SYNC\nfail
FT_Assoc_Drop --> FT_Assoc_Idle: None

'UART thread'
state "<b>Thread UART</b>" as UART
state "<b>UART handshake</b>" as UART_Handshake: <i>Perform handshake over UART with SYNC timestamp</i>
state "<b>UART idle</b>" as UART_Idle: <i>Wait for data to send over UART</i>
state "<b>UART send</b>" as UART_Send: <i>Send queued data over UART</i>
ø
UART --> UART_Handshake: None
UART_Handshake --> UART_Idle: Handshake\nsuccess
UART_Handshake --> UART_Handshake: Handshake\nfail
UART_Idle --> UART_Send: Non-empty\nqueue
UART_Send --> UART_Send: Non-empty\nqueue
UART_Send --> UART_Idle: Empty\nqueue

@enduml
