@startuml
hide empty description

'state "<b>TEMP</b>" as TEMP: <i>TEMP</i>'
state Common: <i>Resources across threads (<b>!!</b> indicate changes to common resources)</i>
state Common: \n- TX socket
state Common: - RX socket
state Common: - UART queue buffer
state Common: - SPI data buffer
state "<b>Common resources</b>" as Common

'Main thread'
state "<b>Thread main</b>" as Main
state "<b>Setup</b>" as Main_Setup: <i>DECT, device and main setup</i>
state Main_Setup {
  state "<b>Start UART thread</b>" as Main_Thread_UART
  state "<b>R-SYNC</b>" as Main_RSYNC: <i>Start Relay-SYNC process as FT</i>
  state "<b>Open sockets</b>" as Main_Sockets: <i>Open TX and RX sockets</i>
  state "<b>Start FT thread</b>" as Main_Thread_FT

  [*]--> Main_Thread_UART
  Main_Thread_UART --> Main_RSYNC: Relay\ndevice
  Main_Thread_UART --> Main_Sockets: Edge\ndevice
  Main_RSYNC --> Main_RSYNC: Timeout\n(<b>n</b> retries)
  Main_RSYNC --> Main_Sockets: SYNC\nsuccess
  Main_Sockets --> Main_Thread_FT: None
  Main_RSYNC --> [*]: SYNC\nfail
}

state "<b>Main idle</b>" as Main_Idle: <i>Listen for data on RX socket</i>
state "<b>UART queue</b>" as Main_UART_Send: <i>Queue data to send on UART</i>

[*] --> Main
Main --> Main_Setup: None
Main_Setup --> Main_Idle: None
Main_Idle --> Main_Idle: Other data received
Main_Idle --> Main_UART_Send: Image data\nreceived
Main_UART_Send --> Main_Idle: None

'FT thread'
state "<b>Thread FT</b>" as FT
state "<b>Channel scan</b>" as FT_Scan: <i>Scan over all channels in band</i>
state "<b>Network beacon</b>" as FT_Beacon: <i>Start network beacon on channel <b>x</b>
state "<b>Association idle" as FT_Assoc_Idle: <i>Wait for association request from PT</i>
state "<b>Association response</b>" as FT_Assoc_Resp: <i>Accept association with PT</i>
state "<b>Association drop</b>" as FT_Assoc_Drop: <i>Drop association with PT</i>
state "<b>SYNC FT" as FT_SYNC: <i>Start SYNC process as FT</i>

FT --> FT_Scan: None
FT_Scan --> FT_Beacon: Best\nchannel <b>x</b>
FT_Beacon --> FT_Assoc_Idle: Beacon\nsuccess
FT_Assoc_Idle --> FT_Beacon: Timeout
FT_Assoc_Idle --> FT_Assoc_Resp: Incoming\nrequest
FT_Assoc_Resp --> FT_Assoc_Idle: Association\nfailed
FT_Assoc_Resp --> FT_SYNC: Association\nsuccess
FT_SYNC --> FT_Assoc_Idle: SYNC\nsuccess
FT_SYNC --> FT_SYNC: Timeout (<b>n</b> retries)
FT_SYNC --> FT_Assoc_Drop: SYNC\nfail
FT_Assoc_Drop --> FT_Assoc_Idle: None

'UART thread'
state "<b>Thread UART</b>" as UART
state "<b>UART init</b>" as UART_Init: <i>Initialize UART connection</i>
state "<b>UART idle</b>" as UART_Idle: <i>Wait for data to send over UART</i>
state "<b>UART send</b>" as UART_Send: <i>Send queued data over UART</i>

UART --> UART_Init: None
UART_Init --> UART_Idle: None
UART_Idle --> UART_Send: Non-empty\nqueue
UART_Send --> UART_Send: Non-empty\nqueue
UART_Send --> UART_Idle: Empty\nqueue

@enduml